/* Auto-generated by extract_weights.py - DO NOT EDIT */
#ifndef DFN3_WEIGHTS_H
#define DFN3_WEIGHTS_H

#include <stddef.h>

#define DFN3_WEIGHTS_SIZE 8538564
#define DFN3_TOTAL_PARAMS 2134641

/* Model configuration from config.ini */
#define DFN3_SR          48000
#define DFN3_FFT_SIZE    960
#define DFN3_HOP_SIZE    480
#define DFN3_FREQ_BINS   481   /* FFT_SIZE/2 + 1 */
#define DFN3_NB_ERB      32
#define DFN3_NB_DF       96
#define DFN3_DF_ORDER    5
#define DFN3_DF_LOOKAHEAD 2
#define DFN3_CONV_CH     64
#define DFN3_EMB_DIM     512
#define DFN3_EMB_HIDDEN  256
#define DFN3_DF_HIDDEN   256
#define DFN3_LSNR_MAX    35
#define DFN3_LSNR_MIN    (-15)
#define DFN3_NORM_TAU    1.0f
#define DFN3_CONV_LOOKAHEAD 2
#define DFN3_ENC_LINEAR_GROUPS 32
#define DFN3_LINEAR_GROUPS 16
#define DFN3_EMB_NUM_LAYERS 3
#define DFN3_DF_NUM_LAYERS 2

typedef struct {
    const float* data;
    int ndim;
    int shape[4];
    int numel;
} DFN3Tensor;

typedef struct {
    /* === Encoder === */
    DFN3Tensor enc_erb_conv1_dw_w;  /* [64, 1, 1, 3] */
    DFN3Tensor enc_erb_conv2_dw_w;  /* [64, 1, 1, 3] */
    DFN3Tensor enc_erb_conv3_dw_w;  /* [64, 1, 1, 3] */
    DFN3Tensor enc_df_conv0_dw_w;  /* [64, 1, 3, 3] */
    DFN3Tensor enc_df_conv1_dw_w;  /* [64, 1, 1, 3] */
    DFN3Tensor enc_df_fc_emb_w;  /* [32, 96, 16] */
    DFN3Tensor enc_emb_gru_lin_in_w;  /* [16, 32, 16] */
    DFN3Tensor enc_emb_gru_lin_out_w;  /* [16, 16, 32] */
    DFN3Tensor enc_lsnr_fc_b;  /* [1] */
    DFN3Tensor enc_erb_conv0_dw_w;  /* [64, 1, 3, 3] */
    DFN3Tensor enc_erb_conv0_dw_b;  /* [64] */
    DFN3Tensor enc_erb_conv1_pw_w;  /* [64, 64, 1, 1] */
    DFN3Tensor enc_erb_conv1_pw_b;  /* [64] */
    DFN3Tensor enc_erb_conv2_pw_w;  /* [64, 64, 1, 1] */
    DFN3Tensor enc_erb_conv2_pw_b;  /* [64] */
    DFN3Tensor enc_erb_conv3_pw_w;  /* [64, 64, 1, 1] */
    DFN3Tensor enc_erb_conv3_pw_b;  /* [64] */
    DFN3Tensor enc_df_conv0_pw_w;  /* [64, 64, 1, 1] */
    DFN3Tensor enc_df_conv0_pw_b;  /* [64] */
    DFN3Tensor enc_df_conv1_pw_w;  /* [64, 64, 1, 1] */
    DFN3Tensor enc_df_conv1_pw_b;  /* [64] */
    DFN3Tensor enc_lsnr_fc_w;  /* [512, 1] */
    DFN3Tensor enc_emb_gru0_W;  /* [1, 768, 256] */
    DFN3Tensor enc_emb_gru0_R;  /* [1, 768, 256] */
    DFN3Tensor enc_emb_gru0_B;  /* [1, 1536] */

    /* === ERB Decoder === */
    DFN3Tensor erb_emb_gru_lin_in_w;  /* [16, 32, 16] */
    DFN3Tensor erb_emb_gru_lin_out_w;  /* [16, 16, 32] */
    DFN3Tensor erb_convt3_dw_w;  /* [64, 1, 1, 3] */
    DFN3Tensor erb_convt2_dw_w;  /* [64, 1, 1, 3] */
    DFN3Tensor erb_convt1_dw_w;  /* [64, 1, 1, 3] */
    DFN3Tensor erb_conv3p_dw_w;  /* [64, 1, 1, 1] */
    DFN3Tensor erb_conv3p_dw_b;  /* [64] */
    DFN3Tensor erb_convt3_pw_w;  /* [64, 64, 1, 1] */
    DFN3Tensor erb_convt3_pw_b;  /* [64] */
    DFN3Tensor erb_conv2p_dw_w;  /* [64, 1, 1, 1] */
    DFN3Tensor erb_conv2p_dw_b;  /* [64] */
    DFN3Tensor erb_convt2_pw_w;  /* [64, 64, 1, 1] */
    DFN3Tensor erb_convt2_pw_b;  /* [64] */
    DFN3Tensor erb_conv1p_dw_w;  /* [64, 1, 1, 1] */
    DFN3Tensor erb_conv1p_dw_b;  /* [64] */
    DFN3Tensor erb_convt1_pw_w;  /* [64, 64, 1, 1] */
    DFN3Tensor erb_convt1_pw_b;  /* [64] */
    DFN3Tensor erb_conv0p_dw_w;  /* [64, 1, 1, 1] */
    DFN3Tensor erb_conv0p_dw_b;  /* [64] */
    DFN3Tensor erb_conv0_out_w;  /* [1, 64, 1, 3] */
    DFN3Tensor erb_conv0_out_b;  /* [1] */
    DFN3Tensor erb_emb_gru0_W;  /* [1, 768, 256] */
    DFN3Tensor erb_emb_gru0_R;  /* [1, 768, 256] */
    DFN3Tensor erb_emb_gru0_B;  /* [1, 1536] */
    DFN3Tensor erb_emb_gru1_W;  /* [1, 768, 256] */
    DFN3Tensor erb_emb_gru1_R;  /* [1, 768, 256] */
    DFN3Tensor erb_emb_gru1_B;  /* [1, 1536] */

    /* === DF Decoder === */
    DFN3Tensor df_convp_dw_w;  /* [10, 32, 5, 1] */
    DFN3Tensor df_gru_lin_in_w;  /* [8, 64, 32] */
    DFN3Tensor df_skip_w;  /* [16, 32, 16] */
    DFN3Tensor df_out_w;  /* [16, 16, 60] */
    DFN3Tensor df_fc_a_b;  /* [1] */
    DFN3Tensor df_convp_pw_w;  /* [10, 10, 1, 1] */
    DFN3Tensor df_convp_pw_b;  /* [10] */
    DFN3Tensor df_gru0_W;  /* [1, 768, 256] */
    DFN3Tensor df_gru0_R;  /* [1, 768, 256] */
    DFN3Tensor df_gru0_B;  /* [1, 1536] */
    DFN3Tensor df_gru1_W;  /* [1, 768, 256] */
    DFN3Tensor df_gru1_R;  /* [1, 768, 256] */
    DFN3Tensor df_gru1_B;  /* [1, 1536] */
    DFN3Tensor df_fc_a_w;  /* [256, 1] */
} DFN3Weights;

static inline void dfn3_weights_init(DFN3Weights* w, const float* base) {
    w->enc_erb_conv1_dw_w = (DFN3Tensor){base + 0, 4, {64, 1, 1, 3}, 192};
    w->enc_erb_conv2_dw_w = (DFN3Tensor){base + 192, 4, {64, 1, 1, 3}, 192};
    w->enc_erb_conv3_dw_w = (DFN3Tensor){base + 384, 4, {64, 1, 1, 3}, 192};
    w->enc_df_conv0_dw_w = (DFN3Tensor){base + 576, 4, {64, 1, 3, 3}, 576};
    w->enc_df_conv1_dw_w = (DFN3Tensor){base + 1152, 4, {64, 1, 1, 3}, 192};
    w->enc_df_fc_emb_w = (DFN3Tensor){base + 1344, 3, {32, 96, 16, 0}, 49152};
    w->enc_emb_gru_lin_in_w = (DFN3Tensor){base + 50496, 3, {16, 32, 16, 0}, 8192};
    w->enc_emb_gru_lin_out_w = (DFN3Tensor){base + 58688, 3, {16, 16, 32, 0}, 8192};
    w->enc_lsnr_fc_b = (DFN3Tensor){base + 66880, 1, {1, 0, 0, 0}, 1};
    w->enc_erb_conv0_dw_w = (DFN3Tensor){base + 66881, 4, {64, 1, 3, 3}, 576};
    w->enc_erb_conv0_dw_b = (DFN3Tensor){base + 67457, 1, {64, 0, 0, 0}, 64};
    w->enc_erb_conv1_pw_w = (DFN3Tensor){base + 67521, 4, {64, 64, 1, 1}, 4096};
    w->enc_erb_conv1_pw_b = (DFN3Tensor){base + 71617, 1, {64, 0, 0, 0}, 64};
    w->enc_erb_conv2_pw_w = (DFN3Tensor){base + 71681, 4, {64, 64, 1, 1}, 4096};
    w->enc_erb_conv2_pw_b = (DFN3Tensor){base + 75777, 1, {64, 0, 0, 0}, 64};
    w->enc_erb_conv3_pw_w = (DFN3Tensor){base + 75841, 4, {64, 64, 1, 1}, 4096};
    w->enc_erb_conv3_pw_b = (DFN3Tensor){base + 79937, 1, {64, 0, 0, 0}, 64};
    w->enc_df_conv0_pw_w = (DFN3Tensor){base + 80001, 4, {64, 64, 1, 1}, 4096};
    w->enc_df_conv0_pw_b = (DFN3Tensor){base + 84097, 1, {64, 0, 0, 0}, 64};
    w->enc_df_conv1_pw_w = (DFN3Tensor){base + 84161, 4, {64, 64, 1, 1}, 4096};
    w->enc_df_conv1_pw_b = (DFN3Tensor){base + 88257, 1, {64, 0, 0, 0}, 64};
    w->enc_lsnr_fc_w = (DFN3Tensor){base + 88321, 2, {512, 1, 0, 0}, 512};
    w->enc_emb_gru0_W = (DFN3Tensor){base + 88833, 3, {1, 768, 256, 0}, 196608};
    w->enc_emb_gru0_R = (DFN3Tensor){base + 285441, 3, {1, 768, 256, 0}, 196608};
    w->enc_emb_gru0_B = (DFN3Tensor){base + 482049, 2, {1, 1536, 0, 0}, 1536};
    w->erb_emb_gru_lin_in_w = (DFN3Tensor){base + 483585, 3, {16, 32, 16, 0}, 8192};
    w->erb_emb_gru_lin_out_w = (DFN3Tensor){base + 491777, 3, {16, 16, 32, 0}, 8192};
    w->erb_convt3_dw_w = (DFN3Tensor){base + 499969, 4, {64, 1, 1, 3}, 192};
    w->erb_convt2_dw_w = (DFN3Tensor){base + 500161, 4, {64, 1, 1, 3}, 192};
    w->erb_convt1_dw_w = (DFN3Tensor){base + 500353, 4, {64, 1, 1, 3}, 192};
    w->erb_conv3p_dw_w = (DFN3Tensor){base + 500545, 4, {64, 1, 1, 1}, 64};
    w->erb_conv3p_dw_b = (DFN3Tensor){base + 500609, 1, {64, 0, 0, 0}, 64};
    w->erb_convt3_pw_w = (DFN3Tensor){base + 500673, 4, {64, 64, 1, 1}, 4096};
    w->erb_convt3_pw_b = (DFN3Tensor){base + 504769, 1, {64, 0, 0, 0}, 64};
    w->erb_conv2p_dw_w = (DFN3Tensor){base + 504833, 4, {64, 1, 1, 1}, 64};
    w->erb_conv2p_dw_b = (DFN3Tensor){base + 504897, 1, {64, 0, 0, 0}, 64};
    w->erb_convt2_pw_w = (DFN3Tensor){base + 504961, 4, {64, 64, 1, 1}, 4096};
    w->erb_convt2_pw_b = (DFN3Tensor){base + 509057, 1, {64, 0, 0, 0}, 64};
    w->erb_conv1p_dw_w = (DFN3Tensor){base + 509121, 4, {64, 1, 1, 1}, 64};
    w->erb_conv1p_dw_b = (DFN3Tensor){base + 509185, 1, {64, 0, 0, 0}, 64};
    w->erb_convt1_pw_w = (DFN3Tensor){base + 509249, 4, {64, 64, 1, 1}, 4096};
    w->erb_convt1_pw_b = (DFN3Tensor){base + 513345, 1, {64, 0, 0, 0}, 64};
    w->erb_conv0p_dw_w = (DFN3Tensor){base + 513409, 4, {64, 1, 1, 1}, 64};
    w->erb_conv0p_dw_b = (DFN3Tensor){base + 513473, 1, {64, 0, 0, 0}, 64};
    w->erb_conv0_out_w = (DFN3Tensor){base + 513537, 4, {1, 64, 1, 3}, 192};
    w->erb_conv0_out_b = (DFN3Tensor){base + 513729, 1, {1, 0, 0, 0}, 1};
    w->erb_emb_gru0_W = (DFN3Tensor){base + 513730, 3, {1, 768, 256, 0}, 196608};
    w->erb_emb_gru0_R = (DFN3Tensor){base + 710338, 3, {1, 768, 256, 0}, 196608};
    w->erb_emb_gru0_B = (DFN3Tensor){base + 906946, 2, {1, 1536, 0, 0}, 1536};
    w->erb_emb_gru1_W = (DFN3Tensor){base + 908482, 3, {1, 768, 256, 0}, 196608};
    w->erb_emb_gru1_R = (DFN3Tensor){base + 1105090, 3, {1, 768, 256, 0}, 196608};
    w->erb_emb_gru1_B = (DFN3Tensor){base + 1301698, 2, {1, 1536, 0, 0}, 1536};
    w->df_convp_dw_w = (DFN3Tensor){base + 1303234, 4, {10, 32, 5, 1}, 1600};
    w->df_gru_lin_in_w = (DFN3Tensor){base + 1304834, 3, {8, 64, 32, 0}, 16384};
    w->df_skip_w = (DFN3Tensor){base + 1321218, 3, {16, 32, 16, 0}, 8192};
    w->df_out_w = (DFN3Tensor){base + 1329410, 3, {16, 16, 60, 0}, 15360};
    w->df_fc_a_b = (DFN3Tensor){base + 1344770, 1, {1, 0, 0, 0}, 1};
    w->df_convp_pw_w = (DFN3Tensor){base + 1344771, 4, {10, 10, 1, 1}, 100};
    w->df_convp_pw_b = (DFN3Tensor){base + 1344871, 1, {10, 0, 0, 0}, 10};
    w->df_gru0_W = (DFN3Tensor){base + 1344881, 3, {1, 768, 256, 0}, 196608};
    w->df_gru0_R = (DFN3Tensor){base + 1541489, 3, {1, 768, 256, 0}, 196608};
    w->df_gru0_B = (DFN3Tensor){base + 1738097, 2, {1, 1536, 0, 0}, 1536};
    w->df_gru1_W = (DFN3Tensor){base + 1739633, 3, {1, 768, 256, 0}, 196608};
    w->df_gru1_R = (DFN3Tensor){base + 1936241, 3, {1, 768, 256, 0}, 196608};
    w->df_gru1_B = (DFN3Tensor){base + 2132849, 2, {1, 1536, 0, 0}, 1536};
    w->df_fc_a_w = (DFN3Tensor){base + 2134385, 2, {256, 1, 0, 0}, 256};
}

#endif /* DFN3_WEIGHTS_H */
